### ISSUE TITLE
ERROR: parameter "TimeZone" can only be set to "UTC"

### ISSUE THREAD

**Issue by rauanmayemir** [MaterializeInc/metabase-materialize-driver#16]
With the latest driver `v0.8.0`, I cannot make the plugin work if I have a custom tz set in my metabase (for displaying timestamps in my time zone, this is not the `JAVA_TIMEZONE` env seting).

```
[80767f05-bf1a-4a52-89d3-def0bcc8ca30] 2021-07-11T13:33:45+03:00 ERROR metabase.driver.sql-jdbc.execute Failed to set timezone 'Asia/Almaty' for :materialize database
io.materialize.util.PSQLException: ERROR: parameter "TimeZone" can only be set to "UTC"
	at io.materialize.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2500)
	at io.materialize.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2235)
	at io.materialize.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
	at io.materialize.jdbc.PgStatement.executeInternal(PgStatement.java:444)
	at io.materialize.jdbc.PgStatement.execute(PgStatement.java:368)
	at io.materialize.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at io.materialize.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at io.materialize.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at io.materialize.jdbc.PgStatement.execute(PgStatement.java:267)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
	at metabase.driver.sql_jdbc.execute$set_time_zone_if_supported_BANG_.invokeStatic(execute.clj:151)
	at metabase.driver.sql_jdbc.execute$set_time_zone_if_supported_BANG_.invoke(execute.clj:136)
	at metabase.driver.sql_jdbc.execute$fn__79638.invokeStatic(execute.clj:183)
	at metabase.driver.sql_jdbc.execute$fn__79638.invoke(execute.clj:178)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:465)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:453)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:462)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:453)
	at metabase.driver.sql_jdbc$fn__81350.invokeStatic(sql_jdbc.clj:54)
	at metabase.driver.sql_jdbc$fn__81350.invoke(sql_jdbc.clj:52)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:68)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:66)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
	at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47664.invoke(mbql_to_native.clj:25)
	at metabase.query_processor.middleware.check_features$check_features$fn__46778.invoke(check_features.clj:39)
	at metabase.query_processor.middleware.limit$limit$fn__47650.invoke(limit.clj:37)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__46230.invoke(cache.clj:211)
	at metabase.query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47910.invoke(optimize_temporal_filters.clj:204)
	at metabase.query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49840.invoke(validate_temporal_bucketing.clj:50)
	at metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45349.invoke(auto_parse_filter_values.clj:43)
	at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41497.invoke(wrap_value_literals.clj:161)
	at metabase.query_processor.middleware.annotate$add_column_info$fn__41372.invoke(annotate.clj:605)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__46650.invoke(permissions.clj:81)
	at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48768.invoke(pre_alias_aggregations.clj:40)
	at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46851.invoke(cumulative_aggregations.clj:60)
	at metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__49067.invoke(resolve_joined_fields.clj:102)
	at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__49380.invoke(resolve_joins.clj:171)
	at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44925.invoke(add_implicit_joins.clj:190)
	at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__47614.invoke(large_int_id.clj:59)
	at metabase.query_processor.middleware.format_rows$format_rows$fn__47595.invoke(format_rows.clj:74)
	at metabase.query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__44219.invoke(add_default_temporal_unit.clj:23)
	at metabase.query_processor.middleware.desugar$desugar$fn__46917.invoke(desugar.clj:21)
	at metabase.query_processor.middleware.binning$update_binning_strategy$fn__45736.invoke(binning.clj:227)
	at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__46453.invoke(resolve_fields.clj:34)
	at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__44574.invoke(add_dimension_projections.clj:314)
	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44803.invoke(add_implicit_clauses.clj:147)
	at metabase.query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49789.invoke(upgrade_field_literals.clj:40)
	at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__45088.invoke(add_source_metadata.clj:123)
	at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48942.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)
	at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45296.invoke(auto_bucket_datetimes.clj:147)
	at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46500.invoke(resolve_source_table.clj:45)
	at metabase.query_processor.middleware.parameters$substitute_parameters$fn__48750.invoke(parameters.clj:111)
	at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46552.invoke(resolve_referenced.clj:79)
	at metabase.query_processor.middleware.expand_macros$expand_macros$fn__47301.invoke(expand_macros.clj:184)
	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__45097.invoke(add_timezone_info.clj:15)
	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49742.invoke(splice_params_in_response.clj:32)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48953$fn__48957.invoke(resolve_database_and_driver.clj:31)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:60)
	at metabase.driver$do_with_driver.invoke(driver.clj:56)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48953.invoke(resolve_database_and_driver.clj:25)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47541.invoke(fetch_source_query.clj:274)
	at metabase.query_processor.middleware.store$initialize_store$fn__49751$fn__49752.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.query_processor.middleware.store$initialize_store$fn__49751.invoke(store.clj:10)
	at metabase.query_processor.middleware.validate$validate_query$fn__49796.invoke(validate.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__47677.invoke(normalize_query.clj:22)
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44943.invoke(add_rows_truncated.clj:35)
	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49727.invoke(results_metadata.clj:147)
	at metabase.query_processor.reducible$async_qp$qp_STAR___38051$thunk__38052.invoke(reducible.clj:103)
	at metabase.query_processor.reducible$async_qp$qp_STAR___38051.invoke(reducible.clj:109)
	at metabase.query_processor.reducible$async_qp$qp_STAR___38051.invoke(reducible.clj:96)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___38060$fn__38061.invoke(reducible.clj:131)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___38060.invoke(reducible.clj:130)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:150)
	at metabase.query_processor$process_query.doInvoke(query_processor.clj:144)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.db.metadata_queries$qp_query$fn__61055.invoke(metadata_queries.clj:21)
	at metabase.db.metadata_queries$qp_query.invokeStatic(metadata_queries.clj:20)
	at metabase.db.metadata_queries$qp_query.invoke(metadata_queries.clj:18)
	at metabase.db.metadata_queries$field_query.invokeStatic(metadata_queries.clj:30)
	at metabase.db.metadata_queries$field_query.invoke(metadata_queries.clj:28)
	at metabase.db.metadata_queries$fn__61075$field_distinct_values__61084$fn__61087.invoke(metadata_queries.clj:75)
	at metabase.db.metadata_queries$fn__61075$field_distinct_values__61084.invoke(metadata_queries.clj:68)
	at metabase.db.metadata_queries$fn__61075$field_distinct_values__61084$fn__61085.invoke(metadata_queries.clj:72)
	at metabase.db.metadata_queries$fn__61075$field_distinct_values__61084.invoke(metadata_queries.clj:68)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.models.field_values$distinct_values.invokeStatic(field_values.clj:132)
	at metabase.models.field_values$distinct_values.invoke(field_values.clj:124)
	at metabase.models.field_values$create_or_update_field_values_BANG_.invokeStatic(field_values.clj:154)
	at metabase.models.field_values$create_or_update_field_values_BANG_.doInvoke(field_values.clj:148)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.sync.field_values$fn__61747$update_field_values_for_field_BANG___61752$fn__61753.invoke(field_values.clj:23)
	at metabase.sync.field_values$fn__61747$update_field_values_for_field_BANG___61752.invoke(field_values.clj:21)
	at metabase.sync.field_values$fn__61773$update_field_values_for_table_BANG___61778$fn__61779$fn__61780$fn__61781.invoke(field_values.clj:44)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:151)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.field_values$fn__61773$update_field_values_for_table_BANG___61778$fn__61779$fn__61780.invoke(field_values.clj:42)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at metabase.sync.field_values$fn__61773$update_field_values_for_table_BANG___61778$fn__61779.invoke(field_values.clj:41)
	at metabase.sync.field_values$fn__61773$update_field_values_for_table_BANG___61778.invoke(field_values.clj:38)
	at clojure.core$map$fn__5866.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
	at clojure.core$chunk_next.invokeStatic(core.clj:708)
	at clojure.core$reduce1.invokeStatic(core.clj:942)
	at clojure.core$reduce1.invokeStatic(core.clj:934)
	at clojure.core$merge_with.invokeStatic(core.clj:3059)
	at clojure.core$merge_with.doInvoke(core.clj:3051)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.field_values$fn__61800$update_field_values_for_database_BANG___61805$fn__61806.invoke(field_values.clj:52)
	at metabase.sync.field_values$fn__61800$update_field_values_for_database_BANG___61805.invoke(field_values.clj:50)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.util$fn__40017$run_step_with_metadata__40022$fn__40026$fn__40028.doInvoke(util.clj:352)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:116)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:113)
	at metabase.sync.util$fn__40017$run_step_with_metadata__40022$fn__40026.invoke(util.clj:347)
	at metabase.sync.util$fn__40017$run_step_with_metadata__40022.invoke(util.clj:342)
	at metabase.sync.util$fn__40208$run_sync_operation__40213$fn__40214$fn__40222.invoke(util.clj:441)
	at metabase.sync.util$fn__40208$run_sync_operation__40213$fn__40214.invoke(util.clj:439)
	at metabase.sync.util$fn__40208$run_sync_operation__40213.invoke(util.clj:433)
	at metabase.sync.field_values$fn__61826$update_field_values_BANG___61831$fn__61832$fn__61833.invoke(field_values.clj:67)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:151)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:147)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver$fn__29667.invokeStatic(driver.clj:527)
	at metabase.driver$fn__29667.invoke(driver.clj:527)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__39929.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__39926.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__39915.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__39910.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__39901.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:169)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:166)
	at metabase.sync.field_values$fn__61826$update_field_values_BANG___61831$fn__61832.invoke(field_values.clj:65)
	at metabase.sync.field_values$fn__61826$update_field_values_BANG___61831.invoke(field_values.clj:61)
	at metabase.api.database$fn__64240$fn__64242.invoke(database.clj:635)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by morsapaes** [comment]
Sorry we missed this, @rauanmayemir! We just shipped native Metabase integration with Materialize v0.12.0 (for 0.41+), so moving forward this driver will no longer be needed to connect and will eventually be deprecated. You can just use the vanilla Postgres connector in Metabase if you upgrade your Materialize instance!

**Comment by bobbyiliev** [comment]
I'm following up on all of the reported issues with the old version of the driver. This should now be fixed with the latest version of the driver.

Materialize will always default to UTC, but even if you have a custom timezone configured in Metabase, it will not cause any errors as Metabase will be aware of the default Materialize timezone.
