### ISSUE TITLE
Error syncing Fields (No fields found for table)

### ISSUE THREAD

**Issue by atroche** [MaterializeInc/metabase-materialize-driver#18]
Hello! I'm having some trouble using the driver.

Metabase version: `v0.41`
materialize-driver.jar version: `0.0.8`
materialize version: `0.9.11`

Here's the symptom:

![image](https://user-images.githubusercontent.com/29839/140641427-3d155f61-50d6-4230-bd56-1970ac7978a9.png)

And I've reproduced some of the logs below:

```
2021-11-07 21:24:05,038 WARN sync.util :: Error syncing Fields for Table 'Table 73 'mz_catalog.mz_metrics''
java.sql.SQLException: Unable to find type name for timestamp with time zone
        at io.materialize.jdbc.TypeInfoCache.getSQLType(TypeInfoCache.java:216)
        at io.materialize.jdbc.PgDatabaseMetaData.getColumns(PgDatabaseMetaData.java:1536)
        at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getColumns(NewProxyDatabaseMetaData.java:3140)
        at metabase.driver.sql_jdbc.sync.describe_table$jdbc_fields_metadata$fn__56290.invoke(describe_table.clj:83)
        at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__56011.reduce(common.clj:34)
        at clojure.core$transduce.invokeStatic(core.clj:6885)
        at clojure.core.Eduction.reduce(core.clj:7684)
        at clojure.core$reduce.invokeStatic(core.clj:6829)
        at clojure.core$cat$fn__8784.invoke(core.clj:7627)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$reduce.invokeStatic(core.clj:6829)
        at clojure.core$reduce.invoke(core.clj:6812)
        at metabase.driver.sql_jdbc.sync.describe_table$fields_metadata$reify__56306.reduce(describe_table.clj:125)
        at clojure.core$transduce.invokeStatic(core.clj:6885)
        at clojure.core$into.invokeStatic(core.clj:6901)                                                                                                       at clojure.core$into.invoke(core.clj:6889)
        at metabase.driver.sql_jdbc.sync.describe_table$describe_table_fields.invokeStatic(describe_table.clj:133)                                             at metabase.driver.sql_jdbc.sync.describe_table$describe_table_fields.doInvoke(describe_table.clj:130)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
```

```
2021-11-07 21:24:04,889 WARN sync.describe-table :: Don't know how to map column type 'oid' to a Field base_type, falling back to :type/*.
2021-11-07 21:24:04,952 WARN sync.describe-table :: Don't know how to map column type 'oid' to a Field base_type, falling back to :type/*.
2021-11-07 21:24:04,952 WARN sync.describe-table :: Don't know how to map column type 'text[]' to a Field base_type, falling back to :type/*.
2021-11-07 21:24:04,965 WARN sync.util :: Error syncing Fields for Table 'Table 65 'mz_catalog.mz_metric_histograms''
java.sql.SQLException: Unable to find type name for jsonb
        at io.materialize.jdbc.TypeInfoCache.getSQLType(TypeInfoCache.java:216)
        at io.materialize.jdbc.PgDatabaseMetaData.getColumns(PgDatabaseMetaData.java:1536)
        at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getColumns(NewProxyDatabaseMetaData.java:3140)
        at metabase.driver.sql_jdbc.sync.describe_table$jdbc_fields_metadata$fn__56290.invoke(describe_table.clj:83)
        at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__56011.reduce(common.clj:34)
```

```
2021-11-07 21:24:04,692 WARN sync.util :: Error syncing Fields for Table 'Table 42 'mz_catalog.mz_dataflow_operator_reachability''
java.sql.SQLException: Unable to find type name for list
        at io.materialize.jdbc.TypeInfoCache.getSQLType(TypeInfoCache.java:216)
        at io.materialize.jdbc.PgDatabaseMetaData.getColumns(PgDatabaseMetaData.java:1536)
        at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getColumns(NewProxyDatabaseMetaData.java:3140)
        at metabase.driver.sql_jdbc.sync.describe_table$jdbc_fields_metadata$fn__56290.invoke(describe_table.clj:83)
        at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__56011.reduce(common.clj:34)
```

**Comment by morsapaes** [comment]
Sorry we missed this, @atroche! We just shipped native Metabase integration with Materialize v0.12.0 (for 0.41+), so moving forward this driver will no longer be needed to connect and will eventually be deprecated. You can just use the vanilla Postgres connector in Metabase if you upgrade your Materialize instance!

**Comment by bobbyiliev** [comment]
Just following up on all of the old issues here:

- The timestamp error should no longer be occurring with the new version of the driver
- The `mz_` schemas have been excluded so they will no longer be synced
